05\1
js-tasks-ru/js-20220418_dmitriy-behterev7 pull request #5
Opened 2022-05-02 15:24 UTC by dbehterev

2022-05-02 15:25 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-05-02 20:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dragozin

2022-05-06 10:56 UTC, dragozin requested changes
Предлагаю поработать над комментариями.

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/1-notification/index.js
> +    msgElNotification.classList.add("notification");
Подобное решение технически работает, но с точки зрения поддержки оно достаточно дорогое. 
Задача по обновлению верстки будет сложнее, чем просто изменить html шаблон.

Поэтому, как совет, более предпочтительное решение - это использовать `innerHTML ` свойство элемента.

Но на нашем проекте можно попробовать все способы, поэтому данное решение так же подходит.

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/1-notification/index.js
> +    msgElNotification.style = `--value:${this.duration / 1000}s`;
Помните важную особенность присвоения к свойству style строки. Свойство style - это объект. Подобное присвоение строки в этот объект на самом деле присваивает значение свойству `cssText`. И могут быть ошибки. Вы присвоили свойству строку и можете ожидать что в данном свойстве будет данная строка, но это не так. Поэтому лучше явно работать со свойством `cssText`

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/1-notification/index.js
> +    let msgElInnerWrapper = document.createElement("div");
Т.к. вы не изменяете данную переменную, то лучше создать ее через ключевое слово `const`

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/1-notification/index.js
> +      console.log("can't remove notification HTML element!");
👍 
так же подойдут методы `console.error` и `console.warn`

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/1-notification/index.js
> +  show(el) {
Данная реализация будет отображать несколько нотификаций, хотя этого хочется избежать. В один момент времени необходимо отображать только одну нотификацию. И если появляется вторая - то уже показанную нотификацию необходимо удалить.
Подумайте, пожалуйста, как это можно сделать.

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/1-notification/index.js
> +    document.body.append(this.element);
функция show как раз принимает родитель, куда необходимо добавить элемент. И если этот родитель передан, то необходимо добавлять именно в него, не в body.

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +            return a[fieldValue].localeCompare(b[fieldValue], ["ru", "en"], {
можно один раз сохранить знак сортировки в константе
```
    const directions = {
      asc: 1,
      desc: -1
    };
    const direction = directions[order];
```

и умножить результат проверки на `direction`, что сократить количество проверок.

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        this.data = this.data.sort((a, b) => {
Функция сортировки - это мутирующая операция. Т.е. массив будет изменен.
Вы получили этот массив из вне. И скопировали ссылку на него в свойство экземпляра класса. 
Но т.к. вы храните ссылку на массив, то у потребителя этот массив так же отсортируется.  Это не предсказуемое поведение. И может привести к ошибкам. 
Представьте у вас есть массив с данными - в одной таблице вы сортируете его по возрастанию, а в другой по убыванию.

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +          elDataHref.append(tmpDiv.firstElementChild); // можно ли так делать?
можно, но он будет перемещен из tmvDiv.
т.е. в tmDiv этого элемента больше не будет

2022-05-06 10:56 UTC, dragozin commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    let root = document.getElementById("root");
явно добавлять в DOM здесь не нужно. Потребитель это сделает сам. Что если нам нужны 2 или 3 таблицы?
Компонент - это универсальный строительный блок. Он не может знать в какой контейнер его поместят, т.к. он должен уметь работать с любым контейнером.

2022-05-15 23:52 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-05-16 07:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dragozin

2022-05-16 10:16 UTC, dbehterev commented on 05-dom-document-loading/1-notification/index.js
> +    msgElNotification.classList.add("notification");
Хорошо, можно тогда так оставлю, в задании №6 на сортировку таблицы версии 2 я переделал на innerHtml.

2022-05-16 10:22 UTC, dbehterev commented on 05-dom-document-loading/1-notification/index.js
> +    msgElNotification.style = `--value:${this.duration / 1000}s`;
исправил.

2022-05-16 10:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dragozin

2022-05-16 10:24 UTC, dbehterev commented on 05-dom-document-loading/1-notification/index.js
> +    let msgElInnerWrapper = document.createElement("div");
исправил.

2022-05-16 10:24 UTC, dbehterev commented on 05-dom-document-loading/1-notification/index.js
> +      console.log("can't remove notification HTML element!");
оставлю так, это больше для отладки.

2022-05-16 10:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dragozin

2022-05-16 10:29 UTC, dbehterev commented on 05-dom-document-loading/1-notification/index.js
> +    document.body.append(this.element);
Вроде я в constructElement() проверяю что это элемент и к нему добавляю, так не подойдет?

2022-05-16 16:02 UTC, dragozin approved these changes

2022-05-16 16:02 UTC, dragozin commented on 05-dom-document-loading/1-notification/index.js
> +    document.body.append(this.element);
Так пойдет конечно, но это решение будет не очень универсальное. 
Вы добавляете в body

а более универсальное решение добавляет в в ваш аргумент `el`
```
el.append(this.element)
```

2022-05-16 16:02 UTC, merged